#!/usr/bin/env bash
set -e

# update the versions
mvn -nsu --settings .github/quarkus-ecosystem-maven-settings.xml -B versions:set-property -Dproperty=quarkus.platform.version -DnewVersion=${QUARKUS_VERSION} -DgenerateBackupPoms=false -Dquarkus.platform.version=${QUARKUS_VERSION}

# run the tests
mvn -nsu --settings .github/quarkus-ecosystem-maven-settings.xml -B clean install -Dnative -Dquarkus.native.container-build=true --fail-at-end -e
