CREATE SEQUENCE application_SEQ START 1 INCREMENT 50;
CREATE SEQUENCE service_SEQ START 1 INCREMENT 50;

CREATE TABLE application
(
  id            BIGINT PRIMARY KEY,
  name          VARCHAR(100) NOT NULL UNIQUE
);