INSERT INTO airports (iata_code, city) VALUES ('MAD', 'Madrid');
INSERT INTO airports (iata_code, city) VALUES ('BCN', 'Barcelona');
INSERT INTO airports (iata_code, city) VALUES ('LHR', 'London');
INSERT INTO airports (iata_code, city) VALUES ('CDG', 'Paris');
INSERT INTO airports (iata_code, city) VALUES ('FRA', 'Frakfurt');
INSERT INTO airports (iata_code, city) VALUES ('IST', 'Istanbul');
INSERT INTO airports (iata_code, city) VALUES ('AMS', 'Amsterdam');
INSERT INTO airports (iata_code, city) VALUES ('FCO', 'Rome');
INSERT INTO airports (iata_code, city) VALUES ('CPH', 'Copenhagen');

INSERT INTO airlines (iata_code, name, infant_price) VALUES ('IB','Iberia',	10);
INSERT INTO airlines (iata_code, name, infant_price) VALUES ('BA','British Airways',15);
INSERT INTO airlines (iata_code, name, infant_price) VALUES ('LH','Lufthansa',7);
INSERT INTO airlines (iata_code, name, infant_price) VALUES ('FR','Ryanair',20);
INSERT INTO airlines (iata_code, name, infant_price) VALUES ('VY','Vueling',10);
INSERT INTO airlines (iata_code, name, infant_price) VALUES ('TK','Turkish Airlines', 5);
INSERT INTO airlines (iata_code, name, infant_price) VALUES ('U2','Easyjet', 19.90);

INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','FRA','IB2818',186);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','LHR','U23631',152);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CDG','MAD','IB8482',295);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('BCN','FRA','FR7521',150);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','FCO','TK4667',137);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','FCO','U24631',268);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FCO','CDG','VY4335',158);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','IST','TK8891',250);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FRA','AMS','U24107',237);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','BCN','U22593',218);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('BCN','IST','VY9890',178);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('AMS','CPH','TK4927',290);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FCO','MAD','BA1164',118);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','LHR','BA7710',138);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('BCN','AMS','U24985',191);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('MAD','CDG','IB9961',128);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','FRA','LH2118',165);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','FRA','IB8911',180);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('AMS','FRA','TK2372',197);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FRA','IST','LH4145',169);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('MAD','CDG','IB6112',112);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','FRA','LH1678',298);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','CPH','LH6620',217);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('MAD','LHR','TK4199',186);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('MAD','CDG','IB7403',253);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FRA','CPH','BA4369',109);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('BCN','MAD','IB2171',259);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','LHR','LH6412',197);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','MAD','LH1115',160);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','LHR','VY8162',285);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FRA','LHR','BA8162',205);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('AMS','FCO','BA7610',168);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','IST','LH1085',148);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FCO','FRA','U21423',274);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','MAD','U23282',113);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CDG','CPH','LH5778',263);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','CDG','BA2777',284);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('BCN','LHR','TK4375',208);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('MAD','FCO','LH8408',149);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('AMS','IST','IB4563',109);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','FCO','LH5174',251);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('MAD','BCN','BA9569',232);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('AMS','FRA','TK2659',248);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','CDG','IB2771',289);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','MAD','IB8688',150);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','AMS','TK8355',137);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FCO','CDG','VY2974',111);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('AMS','FRA','LH5909',113);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','BCN','FR7949',176);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('BCN','CPH','U27858',237);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FRA','AMS','LH2320',288);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','BCN','VY4633',149);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('AMS','IST','IB7289',163);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FRA','LHR','IB9443',254);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','FCO','LH4948',176);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','BCN','TK5558',211);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('BCN','BCN','BA9409',215);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','AMS','FR9261',267);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CDG','IST','IB7181',227);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','BCN','TK1446',217);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FCO','FRA','TK2793',175);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('AMS','CPH','FR1491',284);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','BCN','IB9219',279);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('MAD','AMS','TK7871',159);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FCO','AMS','VY4840',260);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('MAD','FRA','BA8982',171);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','LHR','U23526',254);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FRA','MAD','BA6773',157);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CDG','CPH','IB5257',299);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','CDG','LH8545',230);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','AMS','IB4737',110);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('BCN','MAD','LH5496',293);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CDG','LHR','U29718',103);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','AMS','BA9561',253);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FRA','LHR','TK3167',118);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','FRA','FR4727',108);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CPH','IST','LH6320',115);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','AMS','BA6657',122);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('LHR','FRA','TK5342',295);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','LHR','IB4938',226);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CDG','BCN','VY9791',289);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('MAD','LHR','IB4124',272);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FRA','MAD','BA7842',121);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('AMS','FCO','VY5092',178);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CDG','LHR','BA9813',171);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('FRA','IST','BA2421',226);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('IST','CPH','U28059',262);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('MAD','AMS','LH7260',191);
INSERT INTO flights (origin, destination, flight_code, base_price) VALUES ('CDG','CPH','TK2044',186);

INSERT INTO pricingRules (days_to_departure, until, percentage) VALUES (0,2,150);
INSERT INTO pricingRules (days_to_departure, until, percentage) VALUES (3,15,120);
INSERT INTO pricingRules (days_to_departure, until, percentage) VALUES (16,30,100);
INSERT INTO pricingRules (days_to_departure, until, percentage) VALUES (31,365,80);